repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
-   repo: https://github.com/lunarmodules/luacheck.git
    rev: v1.0.0
    hooks:
    -   id: luacheck
-   repo: https://github.com/JohnnyMorganz/StyLua.git
    rev: v0.15.2
    hooks:
    -   id: stylua
