local devicons = {}

function devicons.setup()
  local colors = {
    c = '#519aba',
    css = '#61afef',
    deb = '#a1b7ee',
    docker = '#384d54',
    html = '#de8c92',
    jpeg = '#c882e7',
    jpg = '#c882e7',
    js = '#ebcb8b',
    jsx = '#519ab8',
    kt = '#7bc99c',
    lock = '#c4c720',
    lua = '#51a0cf',
    mp3 = '#d39ede',
    mp4 = '#9ea3de',
    out = '#abb2bf',
    png = '#c882e7',
    py = '#a3b8ef',
    rb = '#ff75a0',
    robots = '#abb2bf',
    rpm = '#fca2aa',
    rs = '#dea584',
    toml = '#39bf39',
    ts = '#519aba',
    ttf = '#abb2bf',
    vue = '#7bc99c',
    woff = '#abb2bf',
    woff2 = '#abb2bf',
    zip = '#f9d71c',
    md = '#519aba',
  }
  local devicons_ = {
    DevIconC = { fg = colors.c },
    DevIconCss = { fg = colors.css },
    DevIconDeb = { fg = colors.deb },
    DevIconDockerfile = { fg = colors.docker },
    DevIconHtml = { fg = colors.html },
    DevIconJpeg = { fg = colors.jpeg },
    DevIconJpg = { fg = colors.jpg },
    DevIconJs = { fg = colors.js },
    DevIconJsx = { fg = colors.jsx },
    DevIconKotlin = { fg = colors.kt },
    DevIconLock = { fg = colors.lock },
    DevIconLua = { fg = colors.lua },
    DevIconMp3 = { fg = colors.mp3 },
    DevIconMp4 = { fg = colors.mp4 },
    DevIconOut = { fg = colors.out },
    DevIconPng = { fg = colors.png },
    DevIconPy = { fg = colors.py },
    DevIconRb = { fg = colors.rb },
    DevIconRobots = { fg = colors.robots },
    DevIconRpm = { fg = colors.rpm },
    DevIconRs = { fg = colors.rs },
    DevIconToml = { fg = colors.toml },
    DevIconTrueTypeFont = { fg = colors.ttf },
    DevIconTs = { fg = colors.ts },
    DevIconVue = { fg = colors.vue },
    DevIconWebOpenFontFormat = { fg = colors.woff },
    DevIconWebOpenFontFormat2 = { fg = colors.woff2 },
    DevIconXz = { fg = colors.zip },
    DevIconZip = { fg = colors.zip },
    DevIconMd = { fg = colors.md },
  }
  return devicons_
end

return devicons
